# Generated by Django 6.0.2 on 2026-05-04 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_code', models.CharField(editable=False, help_text='Unique tracking code (e.g., AAW-XXXXXX)', max_length=12, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text="Citizen's text description or AI-generated from audio")),
                ('ai_generated_report', models.TextField(blank=True, default='', help_text='AI-generated structured report for government')),
                ('location_text', models.CharField(help_text='Human-readable address', max_length=500)),
                ('latitude', models.FloatField(default=27.7172)),
                ('longitude', models.FloatField(default=85.324)),
                ('status', models.CharField(choices=[('pending_ai', 'Pending AI Analysis'), ('pending_review', 'Pending Moderation'), ('published', 'Published'), ('rejected', 'Rejected'), ('resolved', 'Resolved')], default='pending_ai', max_length=20)),
                ('category', models.CharField(choices=[('roads', 'Roads & Potholes'), ('garbage', 'Garbage & Waste'), ('water', 'Water & Drainage'), ('electricity', 'Electricity & Power'), ('health', 'Health Hazards'), ('education', 'Education & Schools'), ('corruption', 'Corruption'), ('infrastructure', 'Public Infrastructure'), ('other', 'Other')], default='other', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('ai_verdict', models.CharField(blank=True, default='pending', help_text='AI confidence verdict: high, medium, low', max_length=20)),
                ('ai_confidence_score', models.FloatField(default=0.0, help_text='AI confidence score 0.0 - 1.0')),
                ('ai_category_detected', models.CharField(blank=True, default='', max_length=50)),
                ('ai_is_fake', models.BooleanField(default=False)),
                ('ai_urgency', models.BooleanField(default=False, help_text='True if AI detects emergency/urgent situation')),
                ('ai_severity_score', models.IntegerField(default=5, help_text='Severity score 1-10')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='complaints/audio/%Y/%m/')),
                ('transcription', models.TextField(blank=True, default='', help_text='AI-transcribed text from audio')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='complaints.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='complaints/images/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='complaints.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('referred', 'Referred to Department')], max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('officer_name', models.CharField(blank=True, default='', max_length=200)),
                ('department', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='government_actions', to='complaints.complaint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'Approved'), ('reject', 'Rejected'), ('escalate', 'Escalated')], max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='complaints.complaint')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
