# Generated by Django 6.0.2 on 2026-05-10 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity_weight', models.FloatField(default=1.5, help_text='Weight for severity score')),
                ('urgency_weight', models.FloatField(default=2.0, help_text='Weight for urgent complaints')),
                ('recency_weight', models.FloatField(default=1.2, help_text='Weight for recent complaints')),
                ('verification_weight', models.FloatField(default=1.3, help_text='Weight for verified complaints')),
                ('population_weight', models.FloatField(default=1.0, help_text='Population normalization factor')),
                ('recurring_weight', models.FloatField(default=1.4, help_text='Weight for recurring/duplicate issues')),
                ('dbscan_eps_meters', models.FloatField(default=300.0, help_text='DBSCAN radius in meters (epsilon parameter)')),
                ('dbscan_min_samples', models.IntegerField(default=3, help_text='Minimum complaints to form a cluster')),
                ('duplicate_radius_meters', models.FloatField(default=100.0, help_text='GPS proximity radius for duplicate detection')),
                ('duplicate_time_days', models.IntegerField(default=7, help_text='Time window (days) for duplicate detection')),
                ('duplicate_text_threshold', models.FloatField(default=0.5, help_text='Text similarity threshold for duplicate detection (0-1)')),
                ('spam_frequency_limit', models.IntegerField(default=5, help_text='Max complaints from same source in 24h before flagging')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analytics Configuration',
                'verbose_name_plural': 'Analytics Configuration',
            },
        ),
        migrations.CreateModel(
            name='ComplaintCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField(help_text='DBSCAN cluster label (-1 = noise)')),
                ('complaint_count', models.IntegerField(default=0)),
                ('severity_average', models.FloatField(default=0.0)),
                ('density_score', models.FloatField(default=0.0, help_text='Complaint density within cluster radius')),
                ('center_latitude', models.FloatField(default=27.7172)),
                ('center_longitude', models.FloatField(default=85.324)),
                ('radius_meters', models.FloatField(default=0.0, help_text='Approximate radius of the cluster in meters')),
                ('hotspot_priority_score', models.FloatField(default=0.0, help_text='Population-normalized priority score')),
                ('dominant_category', models.CharField(blank=True, default='', help_text='Most common complaint category in this cluster', max_length=20)),
                ('category_breakdown', models.JSONField(blank=True, default=dict, help_text="Category counts: {'roads': 5, 'garbage': 3, ...}")),
                ('ward_name', models.CharField(blank=True, default='', max_length=200)),
                ('unresolved_count', models.IntegerField(default=0, help_text='Number of unresolved complaints in this cluster')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Complaint Cluster',
                'verbose_name_plural': 'Complaint Clusters',
                'ordering': ['-hotspot_priority_score'],
            },
        ),
        migrations.CreateModel(
            name='RegionPopulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(help_text="Ward or area name (e.g., 'KMC Ward 1 - Naxal')", max_length=200, unique=True)),
                ('ward_number', models.IntegerField(default=0, help_text='Numeric ward identifier')),
                ('municipality', models.CharField(default='Kathmandu Metropolitan City', help_text='Municipality this ward belongs to', max_length=200)),
                ('population', models.IntegerField(default=0, help_text='Estimated population count')),
                ('area_km2', models.FloatField(default=1.0, help_text='Area in square kilometers')),
                ('center_latitude', models.FloatField(default=27.7172)),
                ('center_longitude', models.FloatField(default=85.324)),
                ('population_density', models.FloatField(default=0.0, help_text='Auto-computed: population / area_km2')),
            ],
            options={
                'verbose_name': 'Region Population',
                'verbose_name_plural': 'Region Populations',
                'ordering': ['municipality', 'ward_number'],
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='trust_score',
            field=models.FloatField(default=1.0, help_text='Complaint trust score 0.0-1.0 (1.0 = fully trusted)'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ward',
            field=models.CharField(blank=True, default='', help_text='Ward name auto-detected from GPS coordinates', max_length=100),
        ),
        migrations.CreateModel(
            name='HotspotAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(blank=True, default='', max_length=200)),
                ('complaint_count', models.IntegerField(default=0)),
                ('severity_average', models.FloatField(default=0.0)),
                ('priority_score', models.FloatField(default=0.0)),
                ('unresolved_count', models.IntegerField(default=0)),
                ('snapshot_date', models.DateField(auto_now_add=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='complaints.complaintcluster')),
            ],
            options={
                'verbose_name': 'Hotspot Analytics',
                'verbose_name_plural': 'Hotspot Analytics',
                'ordering': ['-snapshot_date', '-priority_score'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(default=0.0, help_text='Similarity score 0.0 - 1.0')),
                ('method', models.CharField(choices=[('gps', 'GPS Proximity'), ('text', 'Text Similarity'), ('combined', 'Combined Score')], default='combined', max_length=10)),
                ('gps_distance_meters', models.FloatField(default=0.0, help_text='Distance between the two complaints in meters')),
                ('text_similarity', models.FloatField(default=0.0, help_text='Text cosine similarity 0.0 - 1.0')),
                ('is_duplicate', models.BooleanField(default=False, help_text='True if system confidently considers these duplicates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_from', to='complaints.complaint')),
                ('complaint_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='complaints.complaint')),
            ],
            options={
                'verbose_name': 'Complaint Similarity',
                'verbose_name_plural': 'Complaint Similarities',
                'ordering': ['-similarity_score'],
                'unique_together': {('complaint_a', 'complaint_b')},
            },
        ),
    ]
