# Generated by Django 5.2.14 on 2026-05-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_analyticsconfig_complaintcluster_regionpopulation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintimage',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Perceptual hash of image for duplicate detection', max_length=64),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='ai_generated_report',
            field=models.TextField(blank=True, default='', help_text='AI-generated structured -report for government'),
        ),
    ]
